[build]
target = "riscv32imc-esp-espidf"

[target.riscv32imc-esp-espidf]
linker    = "ldproxy"
runner    = "espflash flash --monitor" # Select this runner for espflash v2.x.x
rustflags = ["--cfg", "espidf_time64", "-C", "default-linker-libraries"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
CC                         = { value = "../.embuild/espressif/tools/riscv32-esp-elf/esp-2022r1-11.2.0/riscv32-esp-elf/bin/riscv32-esp-elf-gcc", relative = true }
CFLAGS                     = { value = "-fno-pic" }
ESP_IDF_VERSION            = "tag:v5.0.2"
MCU                        = { value = "esp32c3" }
ESP_IDF_TOOLS_INSTALL_DIR  = "custom:../.embuild/espressif"
