[workspace]

members = [
    "signer",
    "broker",
    "parser",
    "auther",
    "tester",
]

exclude = [
    "sphinx-key",
    "crypter"
]

[patch.crates-io]
# updates the "rand" create to use esp RNG
getrandom = { version = "0.2", git = "https://github.com/esp-rs-compat/getrandom.git" }
secp256k1 = { git = "https://github.com/Evanfeenstra/rust-secp256k1", branch = "v0.22.0-new-rand" }
