[package]
name = "sphinx-key-tester"
version = "0.1.0"
authors = ["Evan Feenstra <evanfeenstra@gmail.com>"]
edition = "2018"

[dependencies]
sphinx-key-signer = { path = "../signer" }
sphinx-key-parser = { path = "../parser" }
vls-protocol = { git = "https://gitlab.com/Evanfeenstra/validating-lightning-signer.git", branch = "feature/vls-std" }
vls-protocol-signer = { git = "https://gitlab.com/Evanfeenstra/validating-lightning-signer.git", branch = "feature/vls-std", default-features = false, features = ["secp-lowmemory", "vls-std"] }
anyhow = {version = "1", features = ["backtrace"]}
log = "0.4"
rumqttc = "0.12.0"
tokio = { version = "1.4.0", features = ["rt", "rt-multi-thread", "macros"] }
pretty_env_logger = "0.4.0"
