[package]
name = "sphinx-key"
version = "0.1.0"
authors = ["Evan Feenstra <evanfeenstra@gmail.com>"]
edition = "2018"
resolver = "2"

[profile.release]
opt-level = "s"

[profile.dev]
debug = true # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
default = ["std"]
std = ["sphinx-key-signer"]
pio = ["esp-idf-sys/pio"]
pingpong = []
no_persist = []

[dependencies]
bitflags = "1.3.2"
esp-idf-sys = { version = "0.31.6", features = ["binstart"] }
sphinx-key-signer = { path = "../signer", optional = true }
sphinx-crypter = { git = "https://github.com/stakwork/sphinx-rs.git" }
embedded-svc = "0.22.1"
esp-idf-svc = { version = "0.42.1", features = ["experimental", "alloc"] }
esp-idf-hal = "0.38.0"
embedded-hal = "=1.0.0-alpha.8"
anyhow = {version = "1", features = ["backtrace"]}
log = "0.4"
url = "2"
serde_urlencoded = "0.7.1"
serde = { version = "1.0.137", default-features = false }
serde_json = { version = "1.0.81", default-features = false }
hex = "0.4.3"
rmp-serde = "1.1.0"

[build-dependencies]
embuild = "0.29"
anyhow = "1"

[[bin]]
name = "clear"
path = "src/clear.rs"

