[package]
name = "sphinx-key"
version = "0.1.0"
authors = ["Evan Feenstra <evanfeenstra@gmail.com>"]
edition.workspace = true
rust-version.workspace = true

[features]
default = ["std"]
std = ["sphinx-signer"]
pingpong = []
no_persist = []

[dependencies]
# sphinx-signer = { path = "../../sphinx-rs/signer", optional = true }
sphinx-signer = { git = "https://github.com/stakwork/sphinx-rs.git", optional = true }
# lss-connector = { path = "../../sphinx-rs/lss-connector", default-features = false }
lss-connector = { git = "https://github.com/stakwork/sphinx-rs.git", default-features = false }
sphinx-crypter = { git = "https://github.com/stakwork/sphinx-rs.git" }
url = "2"
serde_urlencoded = "0.7.1"
serde = { version = "1.0.137", default-features = false }
serde_json = { version = "1.0.81", default-features = false }
hex = "0.4.3"
rmp-serde = "1.1.0"

bitflags.workspace = true
esp-idf-sys.workspace = true
embedded-svc.workspace = true
esp-idf-svc.workspace = true
esp-idf-hal.workspace = true
embedded-hal.workspace = true
anyhow.workspace = true
log.workspace = true

[build-dependencies]
embuild.workspace = true

[[bin]]
name = "clear"
path = "src/clear.rs"

[[bin]]
name = "btn"
path = "src/btn.rs"
