[package]
authors      = ["Evan Feenstra <evanfeenstra@gmail.com>"]
edition      = "2021"
name         = "sphinx-key"
rust-version = "1.66"
version      = "0.1.0"

[features]
default    = ["std"]
no_persist = []
pingpong   = []
std        = ["sphinx-signer"]
tls        = []

[dependencies]
hex              = "0.4.3"
serde            = { version = "1.0.137", default-features = false }
serde_json       = { version = "1.0.81", default-features = false }
serde_urlencoded = "0.7.1"
url              = "2"

# sphinx-rs
lss-connector  = { git = "https://github.com/stakwork/sphinx-rs.git", default-features = false, rev = "af50ee91e3600b7b4862e8f00772601c8a342110" }
sphinx-crypter = { git = "https://github.com/stakwork/sphinx-rs.git", rev = "af50ee91e3600b7b4862e8f00772601c8a342110" }
sphinx-signer  = { git = "https://github.com/stakwork/sphinx-rs.git", optional = true, rev = "af50ee91e3600b7b4862e8f00772601c8a342110" }
# local
# lss-connector  = { path = "../../sphinx-rs/lss-connector", default-features = false }
# sphinx-crypter  = { path = "../../sphinx-rs/crypter" }
# sphinx-signer  = { path = "../../sphinx-rs/signer", optional = true }

anyhow.workspace       = true
bitflags.workspace     = true
embedded-hal.workspace = true
embedded-svc.workspace = true
esp-idf-hal.workspace  = true
esp-idf-svc.workspace  = true
esp-idf-sys.workspace  = true
log.workspace          = true

[build-dependencies]
embuild.workspace = true

[[bin]]
name = "clear"
path = "src/clear.rs"

[[bin]]
name = "btn"
path = "src/btn.rs"

