[package]
name = "sphinx-key"
version = "0.1.0"
authors = ["Evan Feenstra <evanfeenstra@gmail.com>"]
edition = "2018"
resolver = "2"

[profile.release]
opt-level = "s"

[profile.dev]
debug = true # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[features]
default = ["std"]
std = ["sphinx-key-signer"]
pio = ["esp-idf-sys/pio"]
pingpong = []

[dependencies]
sphinx-key-signer = { path = "../signer", optional = true }
esp-idf-sys = { version = "0.31.5", features = ["binstart"] }
embedded-svc = { version = "0.21.2" }
esp-idf-svc = "0.41"
esp-idf-hal = "0.37"
embedded-hal = "=1.0.0-alpha.8"
anyhow = {version = "1", features = ["backtrace"]}
log = "0.4"
url = "2"
serde_urlencoded = "0.7.1"
serde = { version = "1.0.137", default-features = false }
serde_json = { version = "1.0.81", default-features = false }

[patch.crates-io]
# Low-memory version of secp256k1 with static precomputation
secp256k1 = { git = "https://github.com/devrandom/rust-secp256k1.git", rev = "4e745ebe7e4c9cd0a7e9c8d5c42e989522e52f71", feature = ["lowmemory"] }

[build-dependencies]
embuild = "0.29"
anyhow = "1"

[[bin]]
name = "clear"
path = "src/clear.rs"

[[bin]]
name = "tiny"
path = "src/tiny.rs"