[package]
authors      = ["Evan Feenstra <evanfeenstra@gmail.com>"]
edition      = "2021"
name         = "sphinx-key"
rust-version = "1.66"
version      = "0.1.0"

[features]
default    = ["std"]
no_persist = []
pingpong   = []
std        = ["sphinx-signer"]

[dependencies]
hex              = "0.4.3"
rmp-serde        = "1.1.0"
serde            = { version = "1.0.137", default-features = false }
serde_json       = { version = "1.0.81", default-features = false }
serde_urlencoded = "0.7.1"
url              = "2"

lss-connector  = { git = "https://github.com/stakwork/sphinx-rs.git", default-features = false, rev = "9c8dc1f8dd61fa908f5546524a9c1d21f1b34dd7" }
# lss-connector  = { path = "../../sphinx-rs/lss-connector", default-features = false }
sphinx-crypter = { git = "https://github.com/stakwork/sphinx-rs.git", rev = "9c8dc1f8dd61fa908f5546524a9c1d21f1b34dd7" }
sphinx-signer  = { git = "https://github.com/stakwork/sphinx-rs.git", optional = true, rev = "9c8dc1f8dd61fa908f5546524a9c1d21f1b34dd7" }
# sphinx-signer  = { path = "../../sphinx-rs/signer", optional = true }

anyhow       = { version = "1", features = ["backtrace"] }
bitflags     = "1.3.2"
embedded-hal = "=1.0.0-alpha.10"
embedded-svc = "0.25.0"
esp-idf-hal  = "0.41.1"
esp-idf-svc  = { version = "0.46.0", features = ["experimental", "alloc"] }
esp-idf-sys  = { version = "0.33.1", features = ["binstart"] }
log          = "0.4.17"

[build-dependencies]
embuild = "0.31.2"

[[bin]]
name = "clear"
path = "src/clear.rs"

[[bin]]
name = "btn"
path = "src/btn.rs"

