[package]
name = "sphinx-key-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
vls-protocol = { path = "../../validating-lightning-signer/vls-protocol" }
serde = { version = "1.0", default-features = false }
serde_bolt = { version = "0.2", default-features = false }

[features]
default = ["std"]
std = ["vls-protocol/std"]

