[build]
target = "riscv32imc-esp-espidf"

[target.riscv32imc-esp-espidf]
linker    = "ldproxy"
runner    = "espflash flash --monitor" # Select this runner for espflash v2.x.x
rustflags = ["--cfg", "espidf_time64", "-C", "default-linker-libraries"]

[unstable]
build-std = ["core", "alloc", "panic_abort"]

[env]
ESP_IDF_VERSION            = "tag:v5.0.2"
MCU                        = "esp32c3"
ESP_IDF_TOOLS_INSTALL_DIR  = "custom:../.embuild/espressif"
