[package]
default-run = "sphinx-key-broker"
edition     = "2021"
name        = "sphinx-key-broker"
version     = "0.1.0"

[profile.release]
strip = "debuginfo"

[dependencies]
anyhow            = { version = "1", features = ["backtrace"] }
async-trait       = "0.1"
bitcoin           = "0.29.0"
chrono            = "0.4"
clap              = "3.2"
clap_derive       = "3.2"
confy             = "0.4.0"
fern              = { version = "0.6", features = ["colored"] }
hex               = "0.4.3"
log               = "0.4"
once_cell         = "1.12.0"
pretty_env_logger = "0.4.0"
rocket            = { version = "0.5.0-rc.2", features = ["json"] }
rumqttc           = "0.12.0"
rumqttd           = { git = "https://github.com/Evanfeenstra/rumqtt", branch = "sphinx-3", features = ["websocket"] }
secp256k1         = { version = "0.24.0", features = ["rand-std", "bitcoin_hashes"] }
serde             = { version = "1.0", features = ["derive"] }
serde_json        = "1.0"
thiserror         = "1.0.31"
toml              = "0.5.9"
url               = { version = "2.2" }

vls-frontend        = { git = "https://gitlab.com/lightning-signer/validating-lightning-signer.git", rev = "de25fc60bce03e9be16a698ffd8e8bdc48ed975d" }
vls-protocol        = { git = "https://gitlab.com/lightning-signer/validating-lightning-signer.git", rev = "de25fc60bce03e9be16a698ffd8e8bdc48ed975d" }
vls-protocol-client = { git = "https://gitlab.com/lightning-signer/validating-lightning-signer.git", rev = "de25fc60bce03e9be16a698ffd8e8bdc48ed975d" }
vls-proxy           = { git = "https://gitlab.com/lightning-signer/validating-lightning-signer.git", rev = "de25fc60bce03e9be16a698ffd8e8bdc48ed975d" }

lss-connector = { git = "https://github.com/stakwork/sphinx-rs", rev = "0843db9ff287f388653089ae95f45cac85fe7a66" }
sphinx-signer = { git = "https://github.com/stakwork/sphinx-rs", rev = "0843db9ff287f388653089ae95f45cac85fe7a66" }
# lss-connector = { path = "../../sphinx-rs/lss-connector" }
# sphinx-signer = { path = "../../sphinx-rs/signer" }

[features]
default = ["std"]
std     = ["vls-protocol/std"]
