[package]
name = "sphinx-key-broker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rumqttd = "0.11.0"
pretty_env_logger = "0.4.0"
confy = "0.4.0"
tokio = "1.18"