[package]
name = "sphinx-key-broker"
version = "0.1.0"
edition = "2021"
default-run = "sphinx-key-broker"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vls-protocol = { git = "https://gitlab.com/lightning-signer/validating-lightning-signer.git" }
vls-proxy = { git = "https://gitlab.com/lightning-signer/validating-lightning-signer.git" }
vls-frontend = { git = "https://gitlab.com/lightning-signer/validating-lightning-signer.git" }
vls-protocol-client = { git = "https://gitlab.com/lightning-signer/validating-lightning-signer.git" }
rumqttd = { git = "https://github.com/Evanfeenstra/rumqtt", branch = "metrics" } 
pretty_env_logger = "0.4.0"
confy = "0.4.0"
sphinx-key-parser = { path = "../parser" }
secp256k1 = { version = "0.24.0", features = ["rand-std", "bitcoin_hashes"] }
anyhow = {version = "1", features = ["backtrace"]}
log = "0.4"
fern = { version = "0.6", features = ["colored"] }
rumqttc = "0.12.0"
clap = "=3.0.0-beta.2"
clap_derive = "=3.0.0-beta.5"
chrono = "0.4"
once_cell = "1.12.0"
bitcoin = "0.29.0"
async-trait = "0.1"
url = { version = "2.2" }
toml = "0.5.9"
rocket = {version = "0.5.0-rc.2", features = ["json"]}
thiserror = "1.0.31"

[features]
default = ["std"]
std = ["vls-protocol/std"]
