[package]
name = "sphinx-key-broker"
version = "0.1.0"
edition = "2021"
default-run = "sphinx-key-broker"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rumqttd = "0.11.0"
pretty_env_logger = "0.4.0"
confy = "0.4.0"
tokio = "1.18"
vls-protocol = { path = "../../validating-lightning-signer/vls-protocol" }
sphinx-key-parser = { path = "../parser" }
secp256k1 = { version = "0.20", features = ["rand-std", "bitcoin_hashes"] }
anyhow = {version = "1", features = ["backtrace"]}
log = "0.4"
rumqttc = "0.12.0"

[features]
default = ["std"]
std = ["vls-protocol/std"]

[[bin]]
name = "test_client"
path = "src/test_client.rs"
# ./target/debug/test_client